version: '3.1'


services:


  db1:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: dbpw
    volumes:
      - ./db1/data:/var/lib/mysql/
      - ./db1/config:/etc/mysql/conf.d/
      - ./db1/log:/var/log/mysql/
    networks:
      db_net:
        ipv4_address: 10.10.10.10
      learning_network:
        ipv4_address: 10.0.0.20
    expose:
      - '3306'
    ports:
      - '3306:3306'
      - '9025:22'
    container_name: DB1


  db2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: dbpw
    volumes:
      - ./db2/data:/var/lib/mysql/
      - ./db2/config:/etc/mysql/conf.d/
      - ./db2/log:/var/log/mysql/
    networks:
      db_net:
        ipv4_address: 10.10.10.20
      learning_network:
        ipv4_address: 10.0.0.21
    expose:
      - '3306'
    ports:
      - '3307:3306'
      - '9026:22'
    container_name: DB2


  adminer:
    image: adminer
    restart: always
    ports:
      - '8001:8080'
    networks:
      db_net:
        ipv4_address: 10.10.10.30
    container_name: Adminer


networks:
  db_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
  learning_network:
    external:
      name: docker_learning_network

